### ISSUE TITLE
Input slider ranges

### ISSUE THREAD

**Issue by xavierlave1** [pkpdapp-team/pkpdapp#61] opened 2020-12-07 15:13 UTC
Trying to input slider ranges from a dcc.Input(), but changing the range actually crashes the Myokit simulation (see branch i60).

**Comment by martinjrobins** [comment] 2020-12-15 10:28
- default/suggested min/max in model table
- overriding min/max linked to both project and model

**Comment by martinjrobins** [comment] 2021-06-15 08:40
duplicate of #124

**Closed by martinjrobins** 2021-06-15 08:40 UTC
